name: Deploy AKS with ACR
on: [workflow_dispatch]
    
jobs:
  deploy-aks:
    runs-on: windows-latest
    
    env:
      aksRgName: rg-chdemo-001
      aksLocation: eastus
      aksClusterName: aks-chdemo-001
      aksClusterNodeCount: 1
      aksk8sversion: 1.22.4
      aksacrName: acrch001
      aksacrSku: Standard
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run az commands'
        shell: powershell
        run: |
          az group create --name ${{ env.aksRgName }} --location ${{ env.aksLocation }}
          az acr create -n ${{ env.aksacrName }} -g ${{ env.aksRgName }} --sku ${{ env.aksacrSku }}
          az aks create --resource-group ${{ env.aksRgName }} --name ${{ env.aksClusterName }} --node-count ${{ env.aksClusterNodeCount }} --kubernetes-version ${{ env.aksk8sversion }} --attach-acr ${{ env.aksacrName }} --generate-ssh-keys
